spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qujingpeng/wechatorder-config
          password: qujingpeng
          username: ********
          basedir: F://baseConfig
  rabbitmq:
    host: 192.168.21.244
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
management:
  endpoints:
    web:
      expose: "*"
  security:
    enabled: false
